name: Build CLI

on:
  push:
    branches: [ master ]
#   pull_request:
#     branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # rid: ['win-x64', 'linux-x64']
        dotnet: [ '3.1.x' ]

    name: ${{ matrix.rid }} Shoko CLI build

    steps:
      - uses: actions/checkout@master
        with:
          submodules: recursive
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet }}
      - run: sudo apt-get update
      - run: sudo apt-get install libicu60
      - run: dotnet restore
      - run: dotnet publish -c Release
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.rid }}
          path: bin/Debug/netstandard2.0/Renamer.Cazzar.*