name: Build CLI

on:
  push:
    branches: [ master ]
#   pull_request:
#     branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # rid: ['win-x64', 'linux-x64']
        dotnet: [ '6.x' ]

    name: ${{ matrix.rid }} build

    steps:
      - uses: actions/checkout@master
        with:
          submodules: recursive
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet }}
      - run: dotnet restore CustomRenamer.csproj
      - run: dotnet publish -c Release CustomRenamer.csproj
      - uses: actions/upload-artifact@v2
        with:
          path: bin/Release/netstandard2.1/Renamer.Cazzar*
